name: Kogito Apps Build

on: [pull_request]

jobs:
  build-chain:
    concurrency:
      group: kogito_apps_pr-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 180
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        maven-version: ['3.8.1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kogito-pipelines/.ci/actions/ubuntu-disk-space@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kogito-pipelines/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kogito-pipelines/.ci/actions/build-chain@main
        with:
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      #I assume that yarn was installed by the maven build in UI packages module
      # TODO: find a way how perform `docker-compose down`
      - name: E2E tests ${{ matrix.java-version }}
        id: e2e
        if: ${{ always() }}
        shell: bash
        run: |
          echo "Run E2E Integration test suite"
          pushd .
          cd kogito-apps/ui-packages
          yarn run test:e2e
          popd
      - name: Surefire Report
        uses: kiegroup/kogito-pipelines/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
