name: Trusty experimental CI

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'trusty/**'
    - 'explainability-service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build kogito-runtimes
      run: git clone https://github.com/kiegroup/kogito-runtimes.git /tmp/kogito-runtimes && mvn clean install -DskipTests -f /tmp/kogito-runtimes/pom.xml     
    - name: Build kogito-apps with experimental flag
      run: mvn -B package --file pom.xml -Pexperimental
